//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id_Flight { get; set; }
        public Nullable<int> Id_Tour { get; set; }
        public Nullable<System.DateTime> DateFlight { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public Nullable<System.TimeSpan> FlightTime { get; set; }
        public Nullable<int> Id_Airplane { get; set; }
        public Nullable<decimal> Price_ticket { get; set; }
    }
}
