//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id_Ticket { get; set; }
        public Nullable<int> Id_Flight { get; set; }
        public Nullable<int> Id_Client { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
