//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int Id_Tour { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_DepartureCity { get; set; }
        public Nullable<int> Id_LandingCity { get; set; }
        public Nullable<int> Id_Airline { get; set; }
        public Nullable<int> CountDays { get; set; }
    }
}
