//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tours()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int Id_Tour { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_DepartureCity { get; set; }
        public Nullable<int> Id_LandingCity { get; set; }
        public Nullable<int> Id_Airline { get; set; }
        public Nullable<int> CountDays { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
